<template>
  <div class="pages--components">
      <zk-address></zk-address>
      <zk-audio></zk-audio>
      <zk-auto-form></zk-auto-form>
      <zk-avatar></zk-avatar>
      <zk-buy-address></zk-buy-address>
      <zk-card></zk-card>
      <zk-cell></zk-cell>
      <zk-countdown></zk-countdown>
      <zk-dialog></zk-dialog>
      <zk-foot></zk-foot>
      <zk-grid></zk-grid>
      <zk-head></zk-head>
      <zk-html></zk-html>
      <zk-image></zk-image>
      <zk-keyword></zk-keyword>
      <zk-list></zk-list>
      <zk-marquee></zk-marquee>
      <zk-mask></zk-mask>
      <zk-nodata></zk-nodata>
      <zk-notice></zk-notice>
      <zk-pay></zk-pay>
      <zk-popup></zk-popup>
      <zk-preview></zk-preview>
      <zk-result></zk-result>
      <zk-search></zk-search>
      <zk-swiper></zk-swiper>
      <zk-tab></zk-tab>
      <zk-table></zk-table>
      <zk-text></zk-text>
      <zk-video></zk-video>
      <zk-backtop></zk-backtop>
      <zk-help-row></zk-help-row>
      <zk-nav></zk-nav>
      <zk-top-nav></zk-top-nav>
      <zk-groupbuy></zk-groupbuy>
      <zk-product-class></zk-product-class>
      <zk-product-item></zk-product-item>

  </div>
</template>
