<template>
  <div class="pages--components">
      <x-agree></x-agree>
      <x-col></x-col>
      <x-component></x-component>
      <x-icon></x-icon>
      <x-image></x-image>
      <x-row></x-row>
      <e-tab-swiper></e-tab-swiper>
      <x-address></x-address>
      <x-audio></x-audio>
      <x-auto-form></x-auto-form>
      <x-avatar></x-avatar>
      <x-button></x-button>
      <x-buy-address></x-buy-address>
      <x-card></x-card>
      <x-cell></x-cell>
      <x-checklist></x-checklist>
      <x-countdown></x-countdown>
      <x-dialog></x-dialog>
      <x-divider></x-divider>
      <x-from></x-from>
      <x-grid></x-grid>
      <x-grid-item></x-grid-item>
      <x-group></x-group>
      <x-groupbuy></x-groupbuy>
      <x-head></x-head>
      <x-html></x-html>
      <x-input></x-input>
      <x-keyword></x-keyword>
      <x-label></x-label>
      <x-lightbox></x-lightbox>
      <x-list></x-list>
      <x-marquee></x-marquee>
      <x-mask></x-mask>
      <x-more></x-more>
      <x-navbar></x-navbar>
      <x-navbar-item></x-navbar-item>
      <x-notice></x-notice>
      <x-number></x-number>
      <x-pay></x-pay>
      <x-picker></x-picker>
      <x-popup></x-popup>
      <x-preview></x-preview>
      <x-product-class></x-product-class>
      <x-radio></x-radio>
      <x-rater></x-rater>
      <x-result></x-result>
      <x-search></x-search>
      <x-searchbar></x-searchbar>
      <x-slider></x-slider>
      <x-spinner></x-spinner>
      <x-swipe></x-swipe>
      <x-swipe-item></x-swipe-item>
      <x-swiper></x-swiper>
      <x-switch></x-switch>
      <x-tab></x-tab>
      <x-tabbar></x-tabbar>
      <x-tabbar-item></x-tabbar-item>
      <x-table></x-table>
      <x-text></x-text>
      <x-textarea></x-textarea>
      <x-title></x-title>
      <x-upload></x-upload>
      <x-verifiy></x-verifiy>
      <x-video></x-video>
      <x-badge></x-badge>
      <x-box></x-box>
      <x-color></x-color>
      <x-nodata></x-nodata>
      <x-foot></x-foot>
      <x-page></x-page>
      <x-product-item></x-product-item>
      <x-top-nav></x-top-nav>
      <x-verifiy-phone></x-verifiy-phone>
      <x-widget></x-widget>

  </div>
</template>
<script>
  export default {
    data () {
      return {
      }
    },
    mounted () {
      this.init()
    },
    methods: {
      async init () {
      }
    }
  }
</script>
