<template>
  <div class="pages--components">
      <x-agree></x-agree>
      <x-col></x-col>
      <x-component></x-component>
      <x-icon></x-icon>
      <x-image></x-image>
      <x-row></x-row>
      <p-backtop></p-backtop>
      <p-help-row></p-help-row>
      <p-nav></p-nav>
      <x-address></x-address>
      <x-audio></x-audio>
      <x-auto-form></x-auto-form>
      <x-avatar></x-avatar>
      <x-button></x-button>
      <x-buy-address></x-buy-address>
      <x-card></x-card>
      <x-cell></x-cell>
      <x-checkbox></x-checkbox>
      <x-checkbox-multipl></x-checkbox-multipl>
      <x-countdown></x-countdown>
      <x-decimal></x-decimal>
      <x-dialog></x-dialog>
      <x-foot></x-foot>
      <x-grid></x-grid>
      <x-groupbuy></x-groupbuy>
      <x-head></x-head>
      <x-html></x-html>
      <x-input></x-input>
      <x-keyword></x-keyword>
      <x-list></x-list>
      <x-marquee></x-marquee>
      <x-mask></x-mask>
      <x-nodata></x-nodata>
      <x-notice></x-notice>
      <x-number></x-number>
      <x-pay></x-pay>
      <x-picker></x-picker>
      <x-popup></x-popup>
      <x-preview></x-preview>
      <x-product-class></x-product-class>
      <x-product-item></x-product-item>
      <x-radio></x-radio>
      <x-result></x-result>
      <x-search></x-search>
      <x-swiper></x-swiper>
      <x-switch></x-switch>
      <x-tab></x-tab>
      <x-table></x-table>
      <x-text></x-text>
      <x-textarea></x-textarea>
      <x-top-nav></x-top-nav>
      <x-upload></x-upload>
      <x-video></x-video>

  </div>
</template>
