<template>
  <div class="pages--components">
	      <x-col></x-col>
      <x-icon></x-icon>
      <x-row></x-row>
      <p-backtop></p-backtop>
      <p-help-row></p-help-row>
      <p-nav></p-nav>
      <p-top-nav></p-top-nav>
      <x-address></x-address>
      <x-audio></x-audio>
      <x-auto-form></x-auto-form>
      <x-avatar></x-avatar>
      <x-buy-address></x-buy-address>
      <x-card></x-card>
      <x-cell></x-cell>
      <x-countdown></x-countdown>
      <x-dialog></x-dialog>
      <x-foot></x-foot>
      <x-grid></x-grid>
      <x-groupbuy></x-groupbuy>
      <x-head></x-head>
      <x-html></x-html>
      <x-image></x-image>
      <x-keyword></x-keyword>
      <x-list></x-list>
      <x-marquee></x-marquee>
      <x-mask></x-mask>
      <x-nodata></x-nodata>
      <x-notice></x-notice>
      <x-pay></x-pay>
      <x-popup></x-popup>
      <x-preview></x-preview>
      <x-product-class></x-product-class>
      <x-product-item></x-product-item>
      <x-result></x-result>
      <x-search></x-search>
      <x-swiper></x-swiper>
      <x-tab></x-tab>
      <x-table></x-table>
      <x-text></x-text>
      <x-video></x-video>

  </div>
</template>
<script>
  export default {
  }
</script>
