const typeMap = {
  1: 'label',
  2: 'textBox',
  3: 'textArea',
  4: 'checkBox',
  5: 'radioButton',
  6: 'dropdownList',
  7: 'numberic',
  8: 'htmlEditBox',
  9: 'datetimePicker',
  10: 'albumUploder',
  11: 'fileUploder',
  12: 'password',
  13: 'hidden',
  14: 'editableDropdownList',
  15: 'switch',
  16: 'listBox',
  17: 'dropDownListMutil',
  18: 'decimal',
  19: 'listBoxMultiple',
  20: 'dateTimePickerRank',
  21: 'checkBoxMultipl',
  30: 'radioButtonMultipl',
  31: 'productCate',
  32: 'productTag',
  33: 'city',
  34: 'email',
  35: 'userTypeGrade',
  40: 'relationTags',
  41: 'relationClass',
  42: 'cityDropList',
  45: 'editor',
  50: 'citySelector',
  51: 'color',
  52: 'bool',
  1001: 'userName',
  1002: 'numberRang',
  1003: 'dateTimeRang',
  1004: 'imagePreview',
  1005: 'json'
}

export default typeMap
